name: auto_rtl
description: Change the direction of TextField, Text,... to RTL/LTR based on the text, and set default direction.
version: 1.0.0
homepage: https://github.com/ShawnAlisson/auto_rtl

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
